### ISSUE TITLE
hello,can you provide the code of Face Reconstruction and Deformation,thanks 

### ISSUE THREAD

**Issue by zeta7337** [halfjoe/3D-Portrait-Stylization#1]

**Comment by halfjoe** [comment]
Hi,

Thanks first for your interest.

Please find the link to download the reconstruction code in Section Face Reconstruction and Deformation -> Usage. The deformation source code will not be released, yet you can use the biharmonic deformation in libigl which will yeild similar results.

Best,
Fangzhou

**Comment by zeta7337** [comment]
> Hi,
> 
> Thanks first for your interest.
> 
> Please find the link to download the reconstruction code in Section Face Reconstruction and Deformation -> Usage. The deformation source code will not be released, yet you can use the biharmonic deformation in libigl which will yeild similar results.
> 
> Best, Fangzhou

thank you!
